FROM tiangolo/uvicorn-gunicorn-fastapi:python3.10

WORKDIR /app

ENV POETRY_VERSION=1.2.0

# Install Poetry
RUN curl -sSL  https://install.python-poetry.org | POETRY_HOME=/opt/poetry python && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry && \
    poetry config experimental.new-installer false && \
    poetry config virtualenvs.create false

# Copy poetry.lock* in case it doesn't exist in the repo
COPY ./pyproject.toml ./poetry.lock* /

# Allow installing dev dependencies to run tests
ARG INSTALL_DEV=false
RUN bash -c poetry install --no-root 

COPY . .
ENV PYTHONPATH=/app