version: "3.1"
services:
  postgres:
    image: postgres:15.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: store_monitor
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
    networks:
      - store_monitor

networks:
  store_monitor:
    driver: bridge
