version: "3.7"

services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: PASSWORD
    volumes:
      - ./volumes/minio:/data
    command: server /data --console-address ":9090"
    networks:
      - store_monitor

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
      /usr/bin/mc rm -r --force myminio/somebucketname;
      /usr/bin/mc mb myminio/somebucketname;
      /usr/bin/mc policy download myminio/somebucketname;
      exit 0;
      "
    networks:
      - store_monitor

  ##########################################################################
  ######                     DATABASE SERVICE                        #######
  ##########################################################################
  postgres:
    image: postgres:15.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: store_monitor
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - store_monitor

  ##########################################################################
  ######                     TASK SERVICE                        #######
  ##########################################################################
  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass redis
    volumes:
      - ./volumes/redis:/data
    networks:
      - store_monitor

  celery:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - .:/app
    command: poetry run celery -A app.worker worker -l info
    depends_on:
      - redis
    networks:
      - store_monitor

  ########################################################################
  ####                     APP SERVICE                        #######
  #######################################################################
  store-monitor-api:
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: >
      /bin/sh -c "
      poetry run uvicorn app.main:fastapiApp --reload --host 0.0.0.0;
      "
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - store_monitor

networks:
  store_monitor:
